### ISSUE TITLE
Future catch not resolved.

### ISSUE THREAD

**Issue by shanehsu** [vapor/async#10]
I wrote a small wrapper for ES6-style `Promise` creation. One of my test does not pass.

```swift
convenience init(_ work: @escaping (_ resolve: (T) -> (), _ reject: (Error) -> ()) -> (),
                 on queue: DispatchQueue = DispatchQueue.global(qos: .background),
                 _ expectation: T.Type = T.self) {
    self.init(expectation)
    queue.async {
        work({ result in self.complete(result) },
             { error in self.fail(error) })
    }
}
```

```swift
func testES6Failure() {
    let expectation = XCTestExpectation()
    
    let promise = Promise<Void>({ _, reject in
        reject(NullError.null)
    })
    promise.future
        .catch { _ in expectation.fulfill() }
    
    wait(for: [expectation], timeout: 5.0)
}
```

One of the two workaround needs to be applied,

```swift
 promise.future.do{ _ in print("A") }.catch { _ in expectation.fulfill() }
```

OR

```swift
let promise = Promise<Void>({ _, reject in
    sleep(1)
    reject(NullError.null)
})
```

**Comment by tanner0101** [comment]
Part of the problem might be that you're using the `.global` dispatch queue. This package _does not_ support concurrent future access. It's designed for using on one thread (event loop).

Try switching to a serial dispatch queue (any queue created with concurrent: false, the default) and see if that helps.

**Comment by shanehsu** [comment]
I changed the constructor to the following,

```swift
convenience init(_ work: @escaping (_ resolve: (T) -> (), _ reject: (Error) -> ()) -> (),
                 on queue: DispatchQueue = .init(label: "com.joueapp.jaasynchelper"),
                 _ expectation: T.Type = T.self) {
    self.init(expectation)
    queue.async {
        work({ result in self.complete(result) },
             { error in self.fail(error) } )
    }
}
```

Essentially creating a serial queue, however, it doesn't work. I suspect what you meant is to do mutating operations on the queue where the `Promise` is created? In this case, the main queue?

Essentially, I need to keep `Promise` and its related `Future` usage in a single serial queue hierarchy?

**Comment by Joannis** [comment]
Could you post a complete example of what you're trying to do and how it's failing? That'd be easier to troubleshoot

**Comment by shanehsu** [comment]
I believe this should reproduce the problem.

https://github.com/shanehsu/vapor-async-bug-report

**Comment by Joannis** [comment]
The bug is because you're using the future on a different thread from the promise's completion. This is not thread-safe.

```swift
import Foundation
import Async

// Supporting code
enum MyError: Error { case anyError }
public extension Promise {
    convenience init(_ work: @escaping (_ resolve: (T) -> (), _ reject: (Error) -> ()) -> (),
                     on queue: DispatchQueue = .init(label: "test-queue"),
                     _ expectation: T.Type = T.self) {
        self.init(expectation)
        queue.async {
            work(self.complete, self.fail)
        }
    }
}

let queue = DispatchQueue(label: "test-queue")

queue.sync {
    let promise = Promise<Void>({ (resolve: () -> (), reject: (Error) -> ()) in
        // usleep(50) // This line would fix the code
        reject(MyError.anyError)
    }, on: queue)

    promise.future.catch { err in
        print("\(err)")
    }
}

RunLoop.current.run(until: .distantFuture)
```

**Comment by shanehsu** [comment]
Point taken. Would it be beneficial that a created a pull request that ultimately make all mutating function run on the same serial queue?
This way, a `Future` would actually own a `DispatchQueue` to which all mutating functions are dispatched.
I believe this could solve future synchronization problems should they arise.

**Comment by Joannis** [comment]
It would solve your issue, but create more issues in the process.

**Comment by Joannis** [comment]
Small addition. You can make your own future/promise system, too. If you comform it to futuretype it integrates with vapor automatically

**Comment by shanehsu** [comment]
Perhaps, that's what I'm afraid of. Closing.

**Comment by Joannis** [comment]
@shaneshu are you in slack? If so, under what name?

**Comment by shanehsu** [comment]
@Joannis hsu.pengjun
