### ISSUE TITLE
Future<Void> to be Completable

### ISSUE THREAD

**Issue by skyweb07** [vapor/async#12]
I would love to have a type alias for `Future<Void>` to be `Completable`, highly inspired from RxSwift one.`Completable` is intended for an action that needs to complete without result, also from my point of view looks better in code than `Future<Void>`

What do you think?

### RxSwift reference

https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Traits.md#completable

**Comment by Joannis** [comment]
I like this 👍

**Comment by Joannis** [comment]
@tanner0101 , your input?

**Comment by Joannis** [comment]
#13
