### ISSUE TITLE
FR - Convenience methods to manage blocking results with timer, etc … Vapor 3.0

### ISSUE THREAD

**Issue by rafiki270** [vapor/async#38]
It would be amazing to have ways to make blocking requests async easy

As Tanner suggested:
```swift
router.get("blocking") { req in
    var result: BlockingResult?
    Thread.async {
        result = blockingStuff()
    }
    
    let promise = Promise(BlockingResult.self)
    
    var source: EventLoopSource?
    source = req.addTimeout(milliseconds: 100) {
        if let result = result {
            promise.complete(result)
            source.cancel()
        }
    }
    source!.resume()
    
    return promise.future
}
```

https://qutheory.slack.com/archives/C4QRYJ6DD/p1516061312000238

**Comment by vzsg** [comment]
Also in that discussion, we talked about how `EVFILT_USER` (kqueue) could be used to eliminate the polling hack, and potentially enable any thread to post notifications to an event loop.

**Comment by tanner0101** [comment]
This has been added!
