### ISSUE TITLE
Refreshing safari on a html file triggers a fatal error in KqueueEventSource.swift

### ISSUE THREAD

**Issue by abbasmousavi** [vapor/async#75]
I am on Safari 11.0.3
Async "1.0.0-rc.1"
and latest Vapor RC

When I refresh Safari on a 406 Byte html file, It triggers this fatal error
```swift
 if response < 0 {
            let reason = String(cString: strerror(errno))
            switch errno {
            case ENOENT: break // event has already been deleted
            default: fatalError("An error occured during KqueueEventSource.update: \(reason)")
            }
        }
```

in KqueueEventSource.swift.  the reason is `Bad file descriptor`. First time the files serves without any problem. Requesting the same file with curl is ok.

**Comment by tanner0101** [comment]
I'm unable to recreate this using Safari Version 11.0.3 (12604.5.6.1.1) and the following project: 

[api-template.zip](https://github.com/vapor/async/files/1765780/api-template.zip)

**Comment by tanner0101** [comment]
Closing this since #76 will cause the crashes to stop. Please let me know if you continue to see any issues here and we can re-open.
