### ISSUE TITLE
Compile error with last swift 4.1 (version 4.1-dev (LLVM 1c8b50929b, Clang 420ae40df6, Swift 7ebaa8a966)

### ISSUE THREAD

**Issue by whirr** [vapor/async#77]
When building the library, all calls to deallocate() are missing the argument 'capacity'.

Here an example:

```
/.build/checkouts/sockets.git-972942978533733666/Sources/TCP/Utilties/TCPAddress.swift:138:35: error: missing argument for parameter 'capacity' in call
            stringData.deallocate()
                                  ^
                                  capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)
```

**Comment by 0xTim** [comment]
@whirr are you 100% sure you're building with Swift 4.1? Because that's the error you get with 4.0. It looks like you're building from the command line? Does `swift --version` print 4.1?

**Comment by whirr** [comment]
The problem was using:

```vapor build```

while using:

```swift build```

the build was successful.
